### ISSUE TITLE
gopkg.in compatibility

### ISSUE THREAD

**Issue by gavv** [yudai/gojsondiff#11]
Hi,

Would you mind to use `vN.M.K` instead of `N.M.K` for tag names, e.g. `v1.0.0`? This way, it would be possible to use [gopkg.in](http://labix.org/gopkg.in) to import stable release, like this:

```go
import "gopkg.in/yudai/gojsondiff.v1"
```

(see http://gopkg.in/yudai/gojsondiff.v1)

You could also add this example to your README.

Notes:

* gopkg.in assumes that the *first* (major) version number should be increased when a breaking change is introduced
* gopkg.in also allows to use branches instead of tags

/link https://github.com/gavv/httpexpect/issues/33 https://github.com/gavv/httpexpect/pull/34

**Comment by yudai** [comment]
Thanks for the comment. I forgot to add `v` to the version number.
Added a new tag with `v`.

**Comment by gavv** [comment]
Great, thanks.
