### ISSUE TITLE
how to deal with diffs of JSON where order of array elements isn't important

### ISSUE THREAD

**Issue by madhukar93** [yudai/gojsondiff#25]
A lot of JSON that I'm dealing with uses arrays as collections where order isn't important. Is there a workaround for this ? I thought of sorting the arrays and then comparing them, but if the JSON to be compared is available as a string then it has to be first deserialized into Go datastructure to sort. I was wondering if there's a simpler way to do this. Thanks for your work !

**Comment by yudai** [comment]
Hi @madhukar93 
Unfortunately, there is no strait forward way to compare arrays as collection.
As you mentioned, I think sorting them before comparing is the way to go.

**Comment by madhukar93** [comment]
thanks, I'll try it out and report with findings if it's anything interesting.
