### ISSUE TITLE
array diff "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by yanyan300300** [yudai/gojsondiff#4]
➜  gojsondiff git:(master) ✗ cat a.json && cat b.json
{
   "arr":[
      "item0",
      "item1"
   ]
}
{
   "arr":[
      "item0",
      "item2",
      "item3"
   ]
}

➜  jd git:(master) ✗ go install && jd -f delta ../a.json ../b.json
panic: runtime error: index out of range

Looks like typo here: https://github.com/yudai/gojsondiff/blob/master/gojsondiff.go#L364

**Comment by shatrugna** [comment]
Came across this issue. This patch fixes it. Thanks @yanyan300300.
Can we pull this in @yudai?

**Comment by yudai** [comment]
Merged! thanks!
